"""add unique on plate_number

Revision ID: 3b0e17e9ef05
Revises: 75421c851649
Create Date: 2020-02-08 09:54:44.104805

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '3b0e17e9ef05'
down_revision = '75421c851649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'truck', ['plate_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'truck', type_='unique')
    # ### end Alembic commands ###
