"""add log_time

Revision ID: 75421c851649
Revises: c7dbf28f1af0
Create Date: 2020-02-07 11:17:14.152219

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '75421c851649'
down_revision = 'c7dbf28f1af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('truckLog', sa.Column('log_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_truckLog_log_time'), 'truckLog', ['log_time'], unique=False)
    op.drop_index('idx_truckLog_geom', table_name='truckLog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_truckLog_geom', 'truckLog', ['geom'], unique=False)
    op.drop_index(op.f('ix_truckLog_log_time'), table_name='truckLog')
    op.drop_column('truckLog', 'log_time')
    # ### end Alembic commands ###
