"""Added initial table

Revision ID: c7dbf28f1af0
Revises:
Create Date: 2020-02-07 09:47:42.243618

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c7dbf28f1af0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('truck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('truckLog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=30, scale=21), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=30, scale=21), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.ForeignKeyConstraint(['truck_id'], ['truck.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('truckLog')
    op.drop_table('truck')
    # ### end Alembic commands ###
